services:
  backend:
    image: backend-minor:latest
    container_name: backend-minor
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8000:8000"
    env_file:
      - ./core/.env
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo
    container_name: mongodb-minor

    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"

  mongodb-express:
    image: mongo-express
    container_name: mongo-express-minor
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
  

volumes:
  mongodb-data: